# docker-compose.yml
version: '2'

services:
  web:
    build:
      # build from Dockerfile
      context: ./
      dockerfile: Dockerfile
    # Flask service port
    ports:
      - "5002:5000"
    # Security Hardening
    cap_drop:
      - ALL
    privileged: false
    read_only: true
    # Tmp
    tmpfs:
      - /tmp
    # Environment Vars
    environment:
      REDISTOGO_URL: redis://redis:6379
      SECRET_KEY: ${SECRET_KEY}
      # Internet Archive
      IA_KEY: ${IA_KEY}
      IA_SECRET: ${IA_SECRET}
      # Slack
      SLACK_API_TOKEN: ${SLACK_API_TOKEN}
      SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}


  redis:
    image: redis
